import type { Metadata } from "next";
import { Barlow, Barlow_Condensed } from "next/font/google";
import { CSSProperties } from "react";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const barlow = Barlow({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const barlowCondensed = Barlow_Condensed({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-bg-primary text-white"
        style={
          {
            "--barlow": barlow.style.fontFamily,
            "--barlowCondensed": barlowCondensed.style.fontFamily,
          } as CSSProperties
        }
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
